### PR TITLE
not entirely sure how to test for material icons being loaded

### PR DESCRIPTION
**Pull request by SignpostMarv**
I've got fontfaceobserver installed via npm (^1.4.12), and I seem to be having trouble getting it to notice that the material icons webfont is loaded whether I'm loading it locally (via bower install) or via the google-hosted font.

I've added a test in this pull request for checking if the google-hosted material icons font has loaded, but I wasn't sure how to get things working :cry: 

If it helps I'm presently using this rather verbose mess to check if it's loaded:

```javascript
var
      ligatureFonts = {
        'Material Icons': { // from https://github.com/google/material-design-icons/blob/master/iconfont/codepoints
          '3d_rotation': '\ue84d'
        }
      }
    ;
    requestAnimationFrame(function(){
      Object.keys(ligatureFonts).forEach(function(fontFamily){
        console.log(fontFamily);
        var
          observer = new FontFaceObserver(fontFamily, {
            featureSettings: 'liga'
          }), // left in from trying to get it to play nice earlier in the evening
          a = document.createElement('span'),
          b = document.createElement('span'),
          c = document.createElement('div'),
          before = Object.keys(ligatureFonts[fontFamily])[0],
          after = ligatureFonts[fontFamily][before],
          widths = [],
          heights = []
        ;
        [a,b,c].forEach(function(el){
          Object.keys(el.style).forEach(function(styleProperty){
            el.style[styleProperty] = 'initial';
          });
          el.style.display = 'inline-block';
        });
        a.textContent = after;
        b.textContent = before;
        c.appendChild(a);
        c.appendChild(b);
        document.body.appendChild(c);
        requestAnimationFrame(function(){
          [a,b].forEach(function(el, i){
            widths[i] = el.offsetWidth;
            heights[i] = el.offsetHeight;
          });
          requestAnimationFrame(function(){
            [a,b].forEach(function(el){
              el.style.fontFamily = fontFamily;
              el.style.webkitFontSmoothing = 'antialiased';
              el.style.textRendering = 'optimizeLegibility';
              el.style.mozOsxFontSmoothing = 'grayscale';
              el.style.fontFeatureSettings = 'liga';
              el.style.fontSize = '16px';
            });
            var
              giveUp = false,
              checkForFont = function(timeout){
                requestAnimationFrame(function(){
                    var
                      hasFont = (
                        a.offsetWidth === b.offsetWidth &&
                        widths[1] !== b.offsetWidth
                      ),
                      fontFamilyAsClass =
                        fontFamily.toLowerCase().replace(/[^a-z0-9]/g, '-')
                    ;
                    if(hasFont){
                      document.head.parentNode.classList.add(
                        'font-loaded_' +
                        fontFamilyAsClass
                      );
                      clearTimeout(timeout);
                    }else if(!giveUp){
                      checkForFont(timeout);
                    }else{
                      document.head.parentNode.classList.add(
                        'font-not-loaded_' +
                        fontFamilyAsClass
                      );
                    }
                });
              }
            ;
            checkForFont(setTimeout(function(){
              giveUp = true;
            }, 5000));
          });
        });
      });
    });
```

### CODE REVIEW

**Comment by bramstein** [comment]
Hey, thanks for creating test cases. They seem to pass on master, are you still having trouble?

**Comment by SignpostMarv** [comment]
I've merged in master & was getting test failure, so I retested it with a more apt icon (font download), all tests pass, minus the null checking, which is presumably expected.

I'm not certain if the named ligature is meant to pass though- is it passing because it's longer than a single character?

**Comment by SignpostMarv** [comment]
added an additional test that checks if it fails to detect a font when the font hasn't been loaded- hope I got the check the right way around :D

**Comment by bramstein** [comment]
Thanks for writing the tests, but I think the existing tests cover this area sufficiently, so I'm closing this pull request. Thanks again!

**Pull request closed without merging**
