### PR TITLE
Support for context argument for specifying another window (to run in an iframe)

### PR DESCRIPTION
**Pull request by codeclown**
Addresses issue https://github.com/bramstein/fontfaceobserver/issues/116.

### CODE REVIEW

**Comment by ngilmore14** [comment]
Also would be helpful for a project

**Comment by alebianco** [comment]
I adopted this variant for a project and it seems to work very well.
You just have to fix the JSDOC of the method because the undocumented parameter is breaking the build process.

**Comment by EloB** [comment]
Why isn't this merged and published?

**Comment by codeclown** [comment]
@alebianco Good catch. See latest commit.

**Comment by mathias-nordicfactory** [comment]
Any progress on getting this PR merged? Really need it for the project I'm working on, thanks 👏

**Comment by baptisteArno** [comment]
Need this as well

**Comment by pranas** [comment]
I rebased this PR and compiled the source code so that it can be installed from GitHub. I do not recommend using [my fork](https://github.com/EddyTravels/fontfaceobserver) directly (not sure how long it will be there) but you can fork it again and then use `npm install <username>/fontfaceobserver` to install from your GitHub fork.

**Comment by bramstein** [comment]
Sorry for the (very!) late response. This looks great, thanks for putting in the effort to make a PR.

**Pull request merged**
