### PR TITLE
Remove dependency on Promises and use a callback.

### PR DESCRIPTION
**Pull request by bramstein**

### CODE REVIEW

**Comment by obto** [comment]
Any status on this being merged? Or have you decided to keep promises after all?

**Comment by bramstein** [comment]
Still undecided, I like the API with promises, but the polyfill adds some overhead.

**Comment by obto** [comment]
For something like this -- where performance is the key concern -- I think it's worth forgoing promises.

It makes the script much lighter. Plus, if you still want promises, a user can easily switch over :)

**Comment by wtayyeb** [comment]
I agree with no Promise support. but if you still undecided you could release two versions, one with promise and the other with callback. but the promise version use the callback version!

**Comment by bramstein** [comment]
OK, I think I'm sold on this. This does mean doing a 2.x release. I have some other API changes planned (basically watching multiple fonts at once to avoid touching the DOM often) that I'd like to roll into a 2.x release. Maybe it is a good idea to start 2.x on a branch and keep patching 1.x until it is ready.

**Comment by jtangelder** [comment]
I would love to see this merged as well.

**Comment by bramstein** [comment]
So a little update on this branch. I've been struggling with this change for three reasons:

1. File size: After removing promises and adding callbacks (and dealing with the consequences of not having promises) the file size was reduced by about 300 bytes gzipped (around 1KB minified). This is not much. 
2. API design: The API works quite nicely because of promises. Callbacks require checking for error codes on each font event. Changing the API would also "break" a lot of existing implementations and articles that use Font Face Observer.
3. Promise support: Browser support for promises has increased in the past two years. See: http://caniuse.com/#search=promise --- they're the future.

I'm not saying this isn't going to happen, but I'm still not certain the benefits outweigh the downsides.

**Comment by jtangelder** [comment]
I think you shouldn't remove Promises, but removing the polyfill is just fine. Browser support is getting better every day, and the Promise polyfill is included in almost every application these days (like when using Babel).

**Comment by bramstein** [comment]
I'm closing this. v1.6.x no longer bundles promises (though still uses them).

**Pull request closed without merging**
