### PR TITLE
Update devDependencies & minor tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
Hey @bramstein.

Only issue grunt@0.4.5, but we can't do a lot apart from forking grunt-closurecompiler.

Let me know if you need me to change something and I will rebase my branch.

### CODE REVIEW

**Comment by bramstein** [comment]
Thanks a lot for doing this. I copied most of your changes (rather than pulling this in because I wanted to work through the changes myself). There are three things I didn't adopt:

* The version ranges for closure-dom and promis. These should be fixed because they are part of the generated code. I don't want them to automatically update unless I verify the build.
* The strict equality checks: they are unnecessary in this case.
* Link to GitHub for the homepage. Font Face Observer now has its own homepage: https://fontfaceobserver.com/

Thanks again, that must have been a lot of work. I really appreciate it!

**Comment by XhmikosR** [comment]
The thing is, the way you did it I'm not the author of the commits.

The git workflow is pretty straight-forward. If you wanted something changed you could have told me like I said in my OP.

**Comment by bramstein** [comment]
Sorry, I didn't realise that was important.

**Comment by XhmikosR** [comment]
Well, giving credits where they are due is always important, regardless of how trivial a patch might be.

Anyway, what's done is done.

**Pull request closed without merging**
