### PR TITLE
Add license notice to dist files to help users to comply with license

### PR DESCRIPTION
**Pull request by DanielaValero**
The license BSD-3-Clause states, that distribution and use of software under this license, must contain the copyright notice and the text of the license.

In order to help users to comply with the license, adding it to the dist files.

Reference link: https://tldrlegal.com/license/bsd-3-clause-license-(revised)

### CODE REVIEW

**Comment by bramstein** [comment]
Hey Daniela! Thanks a lot for creating this pull request. I think it is a good idea to include the license and copyright information in dist files. However, I'm a little worried this might almost double the file size of the dist files. I wonder if we can get away with a shorter message.

**Comment by DanielaValero** [comment]
Hello @bramstein 

I am also with you on the idea that the whole license text is really long for a dist file. 

While working on this PR, I was trying to find other projects with this same license, to check what they do, however could fin only projects with MIT. In them, I could see that the normal pattern is alike what the angular team is using. For example:
https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular-animate.js

```
/**
 * @license AngularJS v1.6.1
 * (c) 2010-2016 Google, Inc. http://angularjs.org
 * License: MIT
 */
```

It seems that for MIT licenses, a note like this is enough. I am not much of an expert on the licensing matter, and don't feel 100% confident that my assessment would be accurate enough to fulfill properly the legal obligations. However, might help to go one step forward. 

So, when we check the MIT license: https://opensource.org/licenses/MIT

I notice that they also ask that not only the copyright but also the full text of the permission is included in the copy. If the short notice that the angular team, helps fulfill the legal obligations, an educated guess for the BSD-3-Clause, would be that the inclusion of the same parts would do the trick too. The parts I identify are:

* Name and version of the package
* Copyright note and year
* Link and name of author
* Name of the license

So, the note would be something like this:

```
FontFaceObserver v2.0.9
Copyright (c) 2014 - Bram Stein
License: BSD-3-Clause
```

However, the requirements of BSD-3-Clause are more strict than MIT, so maybe is good also to add a link to where the full license might be found, perhaps the direct link to the LICENSE file? Just to be safe.

What do you think?

**Comment by bramstein** [comment]
Sorry for the delay on this, I've been busy with other things. How about the following:

```
/* Font Face Observer v<version> - © Bram Stein. License: BSD-3-Clause */
```

That would convey the necessary information, and still be quite small. Thanks!

**Comment by bramstein** [comment]
I've implemented this, and it should be in the next release. Thank you so much for bringing this up and creating a thorough and thoughtful pull request.

**Pull request closed without merging**
